#!/bin/sh
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   script=`readlink -f $0`;
   ap=`dirname $script`;
else
   echo "This script is not, yet, supported on non-Linux systems. We apologize for the inconvenience."
	 exit
fi

# -----------------------------------------------------------------------------------------------------
#                                      Validate Input Data
# -----------------------------------------------------------------------------------------------------

usage="usage: 1. $0 platform
       2. $0 site \"sitename.com\"

  1. Releases new version of the platform (i.e. \"core + sites/all\")
  2. Releases new version of one of the sites in a multisite.
"

if [ $# -eq 1 ]; then 
  if [ $1 = "platform" ]; then
    op="platform"
  fi
fi

if [ $# -eq 2 ]; then
  if [ $1 = "site" ]; then
    op="site"
    sitedomain=$2
  fi
fi

if [ -z $op ]; then
  echo "$usage"
  exit
fi

# -----------------------------------------------------------------------------------------------------
#                                      Configuration
# -----------------------------------------------------------------------------------------------------


username=$(id -un)
timestamp=$(date +"%Y-%m-%d-%H%M%S")

if [ -f "$ap/config.info" ]; then
	source "$ap/config.info"
fi

if [ -z $trunk_location ] || [ -z $releases_location ] || [ -z $sites_location ]; then
  echo "Configuration file missing or not properly filled-out. Please fix."
	echo "Aborting..."
	exit
fi

echo -n "SVN username? [default: $username]: "
read username2

if [[ "$username2" =~ ".*?[a-zA-Z0-9]+.*" ]] ; then
  username=$username2
fi

echo -n "SVN password? "
stty -echo
read password
stty echo
echo ""


#-- make sure the username has permissions/exists
#-- We are using a little trick here, running svn uri check on path we know exists, so the only way it would not work
#-- if authentication is botched.

auth="--username $username --password $password --non-interactive --no-auth-cache --trust-server-cert"

if [ ! "`$ap/dm-build-svn-uri-check -u "$auth" -p $trunk_location`" = "exists" ]; then  
  echo "The username you indicated [$username] does not seem to have permissions on the repo [$trunk_location]"
  echo "Aborting..."
  exit
fi

# -----------------------------------------------------------------------------------------------------
#                                      Execute
# -----------------------------------------------------------------------------------------------------

case "$op" in
'platform')
  $ap/dm-build-platform -t "$timestamp" -c "$core_symlink_name" -u "$auth" -r "$releases_location" -s "$sites_location" -h "$trunk_location"
;;
'site')
  $ap/dm-build-site -t "$timestamp" -u "$auth" -d "$sitedomain" -r "$releases_location" -s "$sites_location" -h "$trunk_location"
;;
esac
  
