#!/bin/sh

while getopts "u:p:" opt; do
  case $opt in
    u) auth=$OPTARG;;
    p) svn_path=$OPTARG;;
  esac
done

if [ -z "$auth" ] || [ -z "$svn_path" ]; then
  exit
fi

svn_info=`svn info $auth --xml $svn_path 2> /dev/null `

if [[ "$svn_info" =~ ".*?<uuid>.*" ]]; then
  echo "exists"
fi